# Generated by Django 2.2 on 2019-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protracker', '0002_auto_20190720_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(default='Dota 2 Hero', max_length=20)),
                ('hero_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('match_date', models.DateTimeField(verbose_name='Match Date')),
                ('heros_lost', models.ManyToManyField(related_name='losts', to='protracker.Hero')),
                ('heros_won', models.ManyToManyField(related_name='wins', to='protracker.Hero')),
            ],
        ),
    ]
