# Generated by Django 2.2 on 2019-07-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0003_hero_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myList', models.TextField(null=True)),
            ],
        ),
    ]
