# Generated by Django 2.2 on 2019-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0004_livematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
