# Generated by Django 2.2 on 2019-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0006_matchestoget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.IntegerField(verbose_name='Match Date'),
        ),
    ]
