# Generated by Django 2.2 on 2019-07-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0008_player_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleToGet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('matchtoget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protracker.MatchesToGet')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protracker.Player')),
            ],
        ),
    ]
