# Generated by Django 2.2 on 2019-07-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0009_roletoget'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_mmr',
            field=models.IntegerField(default=1, verbose_name='MMR'),
        ),
    ]
