# Generated by Django 2.2 on 2019-07-31 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0010_match_match_mmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protracker.Player', unique=True),
        ),
    ]
