# Generated by Django 2.2 on 2019-08-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0012_auto_20190731_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('match', 'player')},
        ),
    ]
