# Generated by Django 2.2 on 2019-08-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0013_auto_20190801_0125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
    ]
