# Generated by Django 2.2 on 2019-08-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protracker', '0014_auto_20190801_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchestoget',
            name='match_mmr',
            field=models.IntegerField(default=1, verbose_name='MMR'),
        ),
    ]
